inherit_from:
  - rubocop.yml
  - rubocop-md.yml
  - rubocop-minitest.yml
  - rubocop-packaging.yml
  - rubocop-performance.yml
  - rubocop-capybara.yml
  - rubocop-erb.yml
  - rubocop-factory_bot.yml
  - rubocop-faker.yml
  - rubocop-haml.yml
  - rubocop-rails.yml
  - rubocop-rake.yml
  - rubocop-rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
